### ISSUE TITLE
Network connection Error using Bringup

### ISSUE THREAD

**Issue by shisha101** [shisha101/ROSRagnarEDU#2]
when using:
`roslaunch ragnar_support bringup.launch robot_ip:=10.0.1.39`
The following errors are thrown, and no joint_states are published

```
[ERROR] [1455878053.903979897]: Failed to receive message length
[ERROR] [1455878053.904030954]: Failed to receive incoming message
[ERROR] [1455878959.022991328]: Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
[ERROR] [1455878959.023044479]: Failed to receive message length
[ERROR] [1455878959.023118025]: Failed to receive incoming message
```

Pinging the robot works fine using`ping 10.0.1.239` however the web interface is not working.
Launching the robot with the default (incorrect) address results in no error messages. This should be changed

**Comment by shisha101** [comment]
@ipa-mirb

**Comment by shisha101** [comment]
Web-interface is now accessible under `http://10.0.1.39/`

**Comment by shisha101** [comment]
**Note**: for the IP to be correctly updated from the **config** file the USB must be unplugged from any PC and the robot must be powered down

**Advice**: make sure the static IP address is free before configuring the **config** file `ping <ip>` is a quick way to do so.

@ipa-mirb, should I start writing a wiki for such tips ?

**Comment by shisha101** [comment]
the only remaining error is this warning that occurs even if the robot has just been turned on

```
[ WARN] [1455897451.576734816]: Tried to connect when socket already in connected state
```

will leave this issue open until its verified to cause no problems

**Comment by ipa-mirb** [comment]
"should I start writing a wiki for such tips ?"
@shisha101 can we write a markdown-syntax tutorial on the main folder of the repo?

**Comment by shisha101** [comment]
Sure, ill start documenting !

**Comment by shisha101** [comment]
the warning mentioned above has been shown to not cause any errors.
