### ISSUE TITLE
Slow motiions cause large vibrations

### ISSUE THREAD

**Issue by shisha101** [shisha101/ROSRagnarEDU#9]
When using the ROS interface or using the G codes, small values of velocities (regardless of point density) cause large vibrations. I would assume this is mainly due to the use of stepper motors.

**Comment by mf-bwf** [comment]
@shisha101 this is due to the motor configuration, the default setup is uses 1/8 microstepping. 
Reconfiguring the system to 1/16 will make slow movements less "jerky".

A reconfiguration involves changing dip-switch setup of the drivers, and changing **"_steps_per_mm"** and **"_max_rate"** values for _alpha, beta, gamma, delta_, joints in the config file.

See documentation on [http://docs.blueworkforce.com](http://docs.blueworkforce.com/ragnar-exp/configuration/stepper-motor)

**Comment by shisha101** [comment]
Thanks for the tip, I looked at the dip-switch setup currently on the robot, it is set such that only pin 2 is high corresponding to a step for 1/2A, using a multimeter I see that the voltage between A+ and A- is 90 volts. the config currently on the robot has **_steps_per_mm** that is 22.22_ which leads me to believe that the microstepping is set to 1/8 and the **_max_rate** is set to 300000.0. I have also noticed that the motors can draw up to 1.8 A but the controller is set to 0.5 A. 

Setting up the switches to w1...w5(1, 0, 1, 0, 1, 0) I got unexpected movements.

from your previous post i understand that the driver should be set up such that w1...w5  (1, 1, 0, 0, 1, 0) when the config file is set to 
**_steps_per_mm** = 44.44_
**_max_rate** = 150000.0
is this correct ?

**Comment by mf-bwf** [comment]
@shisha101 There has been some occurrences, where some of the ST6600 drivers would not work at 1/16 microstep, Even if the driver is set to 1/16 it will still be running at 1/8, making that joint move twice as much as it should. 
This seem to be a problem with the driver itself, and has to be replaced or reverted to running 1/8 microstep. 

Although i have never tried it, you could try to run the system with a mix of 1/16 and 1/8, as long as the **_steps_per_mm** and driver dip switch configuration match, i would not expect any problems.

I would recommend setting
**_steps_per_mm** = 44.44_
**_max_rate** = 64800.0

Driver ST6600
Setting microsteps to 1/16
You can go as high as 4.0A, without to much trouble, the RMS output on the driver are not accurate. If the driver does not get a step pulse within 1 sec, it will go down to half the power. So the motors should not overheat.

Hope this will help

**Comment by shisha101** [comment]
@mf-bwf After doing a bit of testing with the **lower arms removed** (to check if any of the individual drivers had the problem you described), it appears that even if I have the correct settings for the micro step in the **config** file all motors microsteps set for 1/8 **_steps_per_mm** = 22.22_ **_max_rate** =  32400, once I set the dip switch the motors set to 1/8 micro stepping move much faster than the other motors and exceed the set point, compared to the motors left at 1/2A.

**Test case 1**
all motors set to _steps_per_mm = 22.22_ _max_rate =  32400 in config file
motors B, C and D drivers set to 1/2A
motor A driver set to 1/8 microstepping
**result**:
motor A moves with very high velocity and does not stop at the final set-point 
Motor B, C and D move as expected, with controlled velocity and noticeable vibrations

**Test case 2**
all motors set to _steps_per_mm = 22.22_ _max_rate =  32400 in config file
motors A, B and C drivers set to 1/2A
motor D driver set to 1/8 microstepping
**result**:
motor D moves with very high velocity and does not stop at the final set-point 
Motor A, B and C move as expected, with controlled velocity and noticeable vibrations

would you have an idea why this is happening? Am I missing something

**Comment by mf-bwf** [comment]
@shisha101 I am a bit confused about the test cases, it seems that you have mixed up Amp and microsteps.

**_steps_per_mm** should always match microstepping for that specific joint.
44.44_ for 1/16
22.22_ for 1/8
11.11_ for 1/4 

**_max_rate** does not scale with microstepping as it is defined in degrees per minute.
The amperage should not be below 1A, and 2A is a safe setting with your current motors.

Hope you can help me understand the test cases.

**Comment by shisha101** [comment]
@mf-bwf  the way the drivers were set/delivered to us was S1 ... S6 (0 1 0 0 0 0) this corresponds to microstepping 1/2A and 0.5 Amps. This is how 3/4 motors were left during both tests.

regarding the 1/2A microstepping please refer [here](http://www.omc-stepperonline.com/bipolar-stepper-motor-driver-max-4a-current-40vdc-input-16-subdivision-st6600-p-246.html) to **Microstep Selection**

let me know which part of the test cases needs further explanation :)

**Comment by mf-bwf** [comment]
> **Test case 1**
> all motors set to steps_per_mm = 22.22 _max_rate = 32400 in config file
> motors B, C and D drivers set to 1/2A
> motor A driver set to 1/8 microstepping

@shisha101 What confuses me is that motor BCD is set to 0,5Amp and motor A is set to 1/8 microsteps.
Whats the current **and** microstep on each motor.

The default settings we used should be 4A and 1/8 microstep. and that ends up being. 
S1 ... S6 (1 0 1 1 1 1) on the dip switch it says on is down.

**Comment by shisha101** [comment]
> The default settings we used should be 4A and 1/8 microstep. and that ends up being.
> S1 ... S6 (1 0 1 1 1 1) on the dip switch it says on is down.

Ok, I get it now, its not the current that was causing the problem, but the dip switches, "on" was written on the top side **on=1** so I took it that lifted is on ... as in the dip switch up is high is on. 

I just updated the settings of the dips switches, using (1 1 0 1 1 1) (using down as 1 and up as 0) and the config file to **_steps_per_mm** = 44.44_

so currently the motors have 4A 1/16 step on the drivers and **_steps_per_mm** = 44.44_ in the config. They are now smoother and performing better.

**Comment by mf-bwf** [comment]
happy to be able to help, if you need a quick response to technical problems regarding Ragnar feel free to send me a mail.

**Comment by shisha101** [comment]
thanks !, have a good one
